
/**
 * Priority fall through list of url matchers
 * @type {Array}
 */
module.exports = [ 
  require('./ad/bing'),
  require('./ad/google'),
  require('./ad/yahoo'),

  require('./local/bing'),
  require('./local/foursquare'),
  require('./local/groupon'),
  require('./local/livingsocial'),
  require('./local/mapquest'),
  require('./local/opentable'),
  require('./local/yahoo'),
  require('./local/yellowpages'),
  require('./local/yelp'),

	require('./social/facebook'),
	require('./social/googlePlus'),
	require('./social/linkedin'),
	require('./social/pinterest'),
	require('./social/twitter'),
  require('./social/me2day'),
  require('./social/hangouts'),
	require('./social/instagram'),
  require('./social/reddit'),
  require('./social/tumblr'),

	require('./search/360'),
	require('./search/alice'),
	require('./search/alltheweb'),
	require('./search/altavista'),
	require('./search/aol'),
	require('./search/ask'),
	require('./search/auone'),
	require('./search/avg'),
	require('./search/babylon'),
	require('./search/baidu'),
	require('./search/biglobe'),
	require('./search/bing'),
	require('./search/centrum'),
	require('./search/cnn'),
	require('./search/comcast'),
	require('./search/conduit'),
	require('./search/daum'),
	require('./search/docomo'),
	require('./search/eniro'),
	require('./search/globo'),
	require('./search/gomailru'),
	require('./search/goo.ne'),
	require('./search/google'),
	require('./search/incredimail'),
	require('./search/kvasir'),
	require('./search/lycos'),
	require('./search/mamma'),
	require('./search/msn'),
	require('./search/mynet'),
	require('./search/najdi'),
	require('./search/naver'),
	require('./search/netscape'),
	require('./search/onet'),
	require('./search/ozu'),
	require('./search/rakuten'),
	require('./search/rambler'),
	require('./search/search-results'),
	require('./search/sesam'),
	require('./search/seznam'),
	require('./search/so'),
	require('./search/sogou'),
	require('./search/startsiden'),
	require('./search/szukacz'),
	require('./search/terra'),
	require('./search/tutby'),
	require('./search/ukr'),
	require('./search/virgilio'),
	require('./search/voila'),
	require('./search/wirtulana-polska'),
	require('./search/yahoo'),
	require('./search/yam'),
	require('./search/yandex'),

	require('./email/gmail'),
	require('./email/hotmail'),
	require('./email/yahoo'),
  require('./email/naver'),
  require('./email/daum'),

	require('./internal/internal'),

	require('./referral/referral'),

	require('./direct/direct'),

  require('./unknown/unknown')

];